# Generated by IBM TransformationAdvisor
# Wed Jun 08 11:01:35 UTC 2022

FROM ibmcom/websphere-traditional:8.5.5.17-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root {APPLICATION_BINARY} /work/config/{APPLICATION_BINARY}
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
